### ISSUE TITLE
Source of defs.json

### ISSUE THREAD

**Issue by JoelBender** [gtfierro/structured-tag-generation#1]
What is the original source of the `defs.json` file?  I've been around in the [haystackws](https://bitbucket.org/project-haystack/haystackws) project and couldn't find it, maybe this was programmatically created from a mashup of the "trio" files?

**Comment by gtfierro** [comment]
Hi @JoelBender ; The `defs.json` file was programmatically created by Brian from the trio files so it was easier to work with from languages that aren't Fantom. It should contain both the `ph` and the `phIoT` namespaces

**Comment by JoelBender** [comment]
Thanks!
